### ISSUE TITLE
Estructura del proyecto

### ISSUE THREAD

**Issue by gootyfer** [Adalab/c-s1-comecoders#1]
Usad la estructura de ficheros y carpetas que hemos visto en clase para el proyecto:
- carpeta para css
- carpeta para imágenes

**Comment by GemmaBeferull** [comment]
Hecho ;)

**Comment by gootyfer** [comment]
👍

**Comment by gootyfer** [comment]
He visto que tenéis CSS dentro y fuera de la carpeta, así que vuelvo a abrirlo hasta que se solucione

**Comment by Tokytome** [comment]
Ya ta
