### ISSUE TITLE
Nombrado de las clases CSS

### ISSUE THREAD

**Issue by gootyfer** [Adalab/c-s1-comecoders#4]
Por convención, el nombre de las clases CSS comienza por letra minúscula y si tiene varias palabras van separadas por guiones

**Comment by GemmaBeferull** [comment]
Hecho :)

**Comment by gootyfer** [comment]
Sigue habiendo nombre de clase en mayúscula en uno de los tres CSS que tenéis

**Comment by Tokytome** [comment]
Ya ta
